### ISSUE TITLE
Missing commitMsg?

### ISSUE THREAD

**Issue by teebu** [zero88/gh-project-context#17]
Missing `commitMsg`?

This is what I'm seeing:
```
Context output: {
  "branch": "feature/message",
  "onDefaultBranch": false,
  "isPR": true,
  "isReleasePR": false,
  "isTag": false,
  "isManualOrSchedule": false,
  "isMerged": false,
  "isClosed": false,
  "commitId": "9c9d07b89f582278824ac1b56be714e3490ea3d3",
  "shortCommitId": "9b9d07c8",
  "version": "1.7.0b1",
  "isAfterMergedReleasePR": false,
  "ver_current": "1.7.0b1",
  "decision_build": true,
  "decision_publish": false
}
```

i wonder if its because Github Action no longer provides github.event.head_commit.message

**Comment by zero88** [comment]
Hi @teebu 
Currently, `commitMsg` only available in default branch, tag, and merged PR for compute `decision_build`/`decision_publish`/`isAfterMergedReleasePR`
In branch commit, I don't use `commitMsg`, so it is not shown in output.
Could you please share which your usecase when using `commitMsg`, then I can consider add it in output

**Comment by zero88** [comment]
Example in `tag`

```
{
  "branch": "vpnc/v0.9.2",
  "onDefaultBranch": false,
  "isPR": false,
  "isReleasePR": false,
  "isTag": true,
  "isManualOrSchedule": false,
  "isMerged": false,
  "isClosed": false,
  "commitMsg": "Merge pull request #62 from qweio/release/vpnc/0.9.2\n\nVPNC CHANGELOG v0.9.2",
  "commitId": "17f825a533dfa3bd1b45370e57eaffcbcdfdd2e6",
  "shortCommitId": "17f825a5",
  "version": "0.9.2",
  "isAfterMergedReleasePR": false,
  "decision_build": true,
  "decision_publish": true
}
```

**Comment by teebu** [comment]
I'm interested in the commitMsg to use in a notification on pull requests.

**Comment by zero88** [comment]
@teebu Your use-case is reasonable. 
I fixed it in latest version. You can use but tweak a build as [here](
https://github.com/zero88/gh-project-context#latest-commit-message)
