### ISSUE TITLE
Node 12 deprecation warning

### ISSUE THREAD

**Issue by frenchy64** [zero88/gh-project-context#45]
Recently this warning started showing up in my builds:

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: zero88/gh-project-context
```

**Comment by zero88** [comment]
Thank you for the good first issue.

Could you please share the action `zero88/gh-project-context` version you're using?

As latest release `v1.2`, I already used node v16. You might want to upgrade a version to re-check

**Comment by frenchy64** [comment]
I tried the latest commit on master and it did not resolve the issue. I don't know how actions work but I noticed that action.yml refers to node 12 which seemed suspicious enough to open this issue.

-------- Original Message --------

**Comment by zero88** [comment]
ah, okay. You're right. the `action.yml` declares using node v12 in runtime. 
I'm updating it...

**Comment by zero88** [comment]
Resolved
